# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





pkgdatadir = $(datadir)/rtspd
pkgincludedir = $(includedir)/rtspd
pkglibdir = $(libdir)/rtspd
pkglibexecdir = $(libexecdir)/rtspd
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
bin_PROGRAMS = rtspd$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure compile config.guess config.sub \
	depcomp install-sh ltmain.sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
librtspd_la_LIBADD =
am_librtspd_la_OBJECTS = version.lo parese_conf.lo md5c.lo \
	rtsp_comm_fun.lo rtsp_options.lo rtsp_describe.lo \
	rtsp_setup.lo rtsp_play.lo rtsp_teardown.lo rtsp_status.lo \
	rtp_h264.lo rtcp.lo udp.lo tcp.lo socket.lo rtspd.lo
librtspd_la_OBJECTS = $(am_librtspd_la_OBJECTS)
PROGRAMS = $(bin_PROGRAMS)
am_rtspd_OBJECTS = rtspd-version.$(OBJEXT) rtspd-parese_conf.$(OBJEXT) \
	rtspd-md5c.$(OBJEXT) rtspd-rtsp_comm_fun.$(OBJEXT) \
	rtspd-rtsp_options.$(OBJEXT) rtspd-rtsp_describe.$(OBJEXT) \
	rtspd-rtsp_setup.$(OBJEXT) rtspd-rtsp_play.$(OBJEXT) \
	rtspd-rtsp_teardown.$(OBJEXT) rtspd-rtsp_status.$(OBJEXT) \
	rtspd-rtp_h264.$(OBJEXT) rtspd-rtcp.$(OBJEXT) \
	rtspd-udp.$(OBJEXT) rtspd-tcp.$(OBJEXT) rtspd-socket.$(OBJEXT) \
	rtspd-rtspd.$(OBJEXT)
rtspd_OBJECTS = $(am_rtspd_OBJECTS)
rtspd_LDADD = $(LDADD)
rtspd_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(rtspd_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(librtspd_la_SOURCES) $(rtspd_SOURCES)
DIST_SOURCES = $(librtspd_la_SOURCES) $(rtspd_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/sun/IPC2.0/trunk/IPNC_SOURCE/docs/stream/rtspser111/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/sun/IPC2.0/trunk/IPNC_SOURCE/docs/stream/rtspser111/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /home/sun/IPC2.0/trunk/IPNC_SOURCE/docs/stream/rtspser111/missing --run autoconf
AUTOHEADER = ${SHELL} /home/sun/IPC2.0/trunk/IPNC_SOURCE/docs/stream/rtspser111/missing --run autoheader
AUTOMAKE = ${SHELL} /home/sun/IPC2.0/trunk/IPNC_SOURCE/docs/stream/rtspser111/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld
LDFLAGS = 
LIBOBJS = 
LIBS = -lpthread 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/sun/IPC2.0/trunk/IPNC_SOURCE/docs/stream/rtspser111/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = rtspd
PACKAGE_BUGREPORT = 
PACKAGE_NAME = rtspd
PACKAGE_STRING = rtspd 1.0
PACKAGE_TARNAME = rtspd
PACKAGE_URL = 
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 1.0
abs_builddir = /home/sun/IPC2.0/trunk/IPNC_SOURCE/docs/stream/rtspser111
abs_srcdir = /home/sun/IPC2.0/trunk/IPNC_SOURCE/docs/stream/rtspser111
abs_top_builddir = /home/sun/IPC2.0/trunk/IPNC_SOURCE/docs/stream/rtspser111
abs_top_srcdir = /home/sun/IPC2.0/trunk/IPNC_SOURCE/docs/stream/rtspser111
ac_ct_CC = gcc
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/sun/IPC2.0/trunk/IPNC_SOURCE/docs/stream/rtspser111/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lt_ECHO = echo
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign
rtspd_SOURCES = comm/version.c comm/parese_conf.c comm/md5c.c rtsp/rtsp_comm_fun.c rtsp/rtsp_options.c rtsp/rtsp_describe.c \
							rtsp/rtsp_setup.c rtsp/rtsp_play.c rtsp/rtsp_teardown.c rtsp/rtsp_status.c \
						  rtp/rtp_h264.c rtcp/rtcp.c  rtp/udp.c rtp/tcp.c net/socket.c rtspd.c

rtspd_CFLAGS = $(AM_CFLAGS)
lib_LTLIBRARIES = librtspd.la
librtspd_la_SOURCES = comm/version.c comm/parese_conf.c comm/md5c.c rtsp/rtsp_comm_fun.c rtsp/rtsp_options.c rtsp/rtsp_describe.c \
							rtsp/rtsp_setup.c rtsp/rtsp_play.c rtsp/rtsp_teardown.c rtsp/rtsp_status.c \
						  rtp/rtp_h264.c rtcp/rtcp.c  rtp/udp.c rtp/tcp.c net/socket.c rtspd.c

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
librtspd.la: $(librtspd_la_OBJECTS) $(librtspd_la_DEPENDENCIES) 
	$(LINK) -rpath $(libdir) $(librtspd_la_OBJECTS) $(librtspd_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
rtspd$(EXEEXT): $(rtspd_OBJECTS) $(rtspd_DEPENDENCIES) 
	@rm -f rtspd$(EXEEXT)
	$(rtspd_LINK) $(rtspd_OBJECTS) $(rtspd_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/md5c.Plo
include ./$(DEPDIR)/parese_conf.Plo
include ./$(DEPDIR)/rtcp.Plo
include ./$(DEPDIR)/rtp_h264.Plo
include ./$(DEPDIR)/rtsp_comm_fun.Plo
include ./$(DEPDIR)/rtsp_describe.Plo
include ./$(DEPDIR)/rtsp_options.Plo
include ./$(DEPDIR)/rtsp_play.Plo
include ./$(DEPDIR)/rtsp_setup.Plo
include ./$(DEPDIR)/rtsp_status.Plo
include ./$(DEPDIR)/rtsp_teardown.Plo
include ./$(DEPDIR)/rtspd-md5c.Po
include ./$(DEPDIR)/rtspd-parese_conf.Po
include ./$(DEPDIR)/rtspd-rtcp.Po
include ./$(DEPDIR)/rtspd-rtp_h264.Po
include ./$(DEPDIR)/rtspd-rtsp_comm_fun.Po
include ./$(DEPDIR)/rtspd-rtsp_describe.Po
include ./$(DEPDIR)/rtspd-rtsp_options.Po
include ./$(DEPDIR)/rtspd-rtsp_play.Po
include ./$(DEPDIR)/rtspd-rtsp_setup.Po
include ./$(DEPDIR)/rtspd-rtsp_status.Po
include ./$(DEPDIR)/rtspd-rtsp_teardown.Po
include ./$(DEPDIR)/rtspd-rtspd.Po
include ./$(DEPDIR)/rtspd-socket.Po
include ./$(DEPDIR)/rtspd-tcp.Po
include ./$(DEPDIR)/rtspd-udp.Po
include ./$(DEPDIR)/rtspd-version.Po
include ./$(DEPDIR)/rtspd.Plo
include ./$(DEPDIR)/socket.Plo
include ./$(DEPDIR)/tcp.Plo
include ./$(DEPDIR)/udp.Plo
include ./$(DEPDIR)/version.Plo

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

version.lo: comm/version.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT version.lo -MD -MP -MF $(DEPDIR)/version.Tpo -c -o version.lo `test -f 'comm/version.c' || echo '$(srcdir)/'`comm/version.c
	$(am__mv) $(DEPDIR)/version.Tpo $(DEPDIR)/version.Plo
#	source='comm/version.c' object='version.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o version.lo `test -f 'comm/version.c' || echo '$(srcdir)/'`comm/version.c

parese_conf.lo: comm/parese_conf.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT parese_conf.lo -MD -MP -MF $(DEPDIR)/parese_conf.Tpo -c -o parese_conf.lo `test -f 'comm/parese_conf.c' || echo '$(srcdir)/'`comm/parese_conf.c
	$(am__mv) $(DEPDIR)/parese_conf.Tpo $(DEPDIR)/parese_conf.Plo
#	source='comm/parese_conf.c' object='parese_conf.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o parese_conf.lo `test -f 'comm/parese_conf.c' || echo '$(srcdir)/'`comm/parese_conf.c

md5c.lo: comm/md5c.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT md5c.lo -MD -MP -MF $(DEPDIR)/md5c.Tpo -c -o md5c.lo `test -f 'comm/md5c.c' || echo '$(srcdir)/'`comm/md5c.c
	$(am__mv) $(DEPDIR)/md5c.Tpo $(DEPDIR)/md5c.Plo
#	source='comm/md5c.c' object='md5c.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o md5c.lo `test -f 'comm/md5c.c' || echo '$(srcdir)/'`comm/md5c.c

rtsp_comm_fun.lo: rtsp/rtsp_comm_fun.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rtsp_comm_fun.lo -MD -MP -MF $(DEPDIR)/rtsp_comm_fun.Tpo -c -o rtsp_comm_fun.lo `test -f 'rtsp/rtsp_comm_fun.c' || echo '$(srcdir)/'`rtsp/rtsp_comm_fun.c
	$(am__mv) $(DEPDIR)/rtsp_comm_fun.Tpo $(DEPDIR)/rtsp_comm_fun.Plo
#	source='rtsp/rtsp_comm_fun.c' object='rtsp_comm_fun.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rtsp_comm_fun.lo `test -f 'rtsp/rtsp_comm_fun.c' || echo '$(srcdir)/'`rtsp/rtsp_comm_fun.c

rtsp_options.lo: rtsp/rtsp_options.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rtsp_options.lo -MD -MP -MF $(DEPDIR)/rtsp_options.Tpo -c -o rtsp_options.lo `test -f 'rtsp/rtsp_options.c' || echo '$(srcdir)/'`rtsp/rtsp_options.c
	$(am__mv) $(DEPDIR)/rtsp_options.Tpo $(DEPDIR)/rtsp_options.Plo
#	source='rtsp/rtsp_options.c' object='rtsp_options.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rtsp_options.lo `test -f 'rtsp/rtsp_options.c' || echo '$(srcdir)/'`rtsp/rtsp_options.c

rtsp_describe.lo: rtsp/rtsp_describe.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rtsp_describe.lo -MD -MP -MF $(DEPDIR)/rtsp_describe.Tpo -c -o rtsp_describe.lo `test -f 'rtsp/rtsp_describe.c' || echo '$(srcdir)/'`rtsp/rtsp_describe.c
	$(am__mv) $(DEPDIR)/rtsp_describe.Tpo $(DEPDIR)/rtsp_describe.Plo
#	source='rtsp/rtsp_describe.c' object='rtsp_describe.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rtsp_describe.lo `test -f 'rtsp/rtsp_describe.c' || echo '$(srcdir)/'`rtsp/rtsp_describe.c

rtsp_setup.lo: rtsp/rtsp_setup.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rtsp_setup.lo -MD -MP -MF $(DEPDIR)/rtsp_setup.Tpo -c -o rtsp_setup.lo `test -f 'rtsp/rtsp_setup.c' || echo '$(srcdir)/'`rtsp/rtsp_setup.c
	$(am__mv) $(DEPDIR)/rtsp_setup.Tpo $(DEPDIR)/rtsp_setup.Plo
#	source='rtsp/rtsp_setup.c' object='rtsp_setup.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rtsp_setup.lo `test -f 'rtsp/rtsp_setup.c' || echo '$(srcdir)/'`rtsp/rtsp_setup.c

rtsp_play.lo: rtsp/rtsp_play.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rtsp_play.lo -MD -MP -MF $(DEPDIR)/rtsp_play.Tpo -c -o rtsp_play.lo `test -f 'rtsp/rtsp_play.c' || echo '$(srcdir)/'`rtsp/rtsp_play.c
	$(am__mv) $(DEPDIR)/rtsp_play.Tpo $(DEPDIR)/rtsp_play.Plo
#	source='rtsp/rtsp_play.c' object='rtsp_play.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rtsp_play.lo `test -f 'rtsp/rtsp_play.c' || echo '$(srcdir)/'`rtsp/rtsp_play.c

rtsp_teardown.lo: rtsp/rtsp_teardown.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rtsp_teardown.lo -MD -MP -MF $(DEPDIR)/rtsp_teardown.Tpo -c -o rtsp_teardown.lo `test -f 'rtsp/rtsp_teardown.c' || echo '$(srcdir)/'`rtsp/rtsp_teardown.c
	$(am__mv) $(DEPDIR)/rtsp_teardown.Tpo $(DEPDIR)/rtsp_teardown.Plo
#	source='rtsp/rtsp_teardown.c' object='rtsp_teardown.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rtsp_teardown.lo `test -f 'rtsp/rtsp_teardown.c' || echo '$(srcdir)/'`rtsp/rtsp_teardown.c

rtsp_status.lo: rtsp/rtsp_status.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rtsp_status.lo -MD -MP -MF $(DEPDIR)/rtsp_status.Tpo -c -o rtsp_status.lo `test -f 'rtsp/rtsp_status.c' || echo '$(srcdir)/'`rtsp/rtsp_status.c
	$(am__mv) $(DEPDIR)/rtsp_status.Tpo $(DEPDIR)/rtsp_status.Plo
#	source='rtsp/rtsp_status.c' object='rtsp_status.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rtsp_status.lo `test -f 'rtsp/rtsp_status.c' || echo '$(srcdir)/'`rtsp/rtsp_status.c

rtp_h264.lo: rtp/rtp_h264.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rtp_h264.lo -MD -MP -MF $(DEPDIR)/rtp_h264.Tpo -c -o rtp_h264.lo `test -f 'rtp/rtp_h264.c' || echo '$(srcdir)/'`rtp/rtp_h264.c
	$(am__mv) $(DEPDIR)/rtp_h264.Tpo $(DEPDIR)/rtp_h264.Plo
#	source='rtp/rtp_h264.c' object='rtp_h264.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rtp_h264.lo `test -f 'rtp/rtp_h264.c' || echo '$(srcdir)/'`rtp/rtp_h264.c

rtcp.lo: rtcp/rtcp.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT rtcp.lo -MD -MP -MF $(DEPDIR)/rtcp.Tpo -c -o rtcp.lo `test -f 'rtcp/rtcp.c' || echo '$(srcdir)/'`rtcp/rtcp.c
	$(am__mv) $(DEPDIR)/rtcp.Tpo $(DEPDIR)/rtcp.Plo
#	source='rtcp/rtcp.c' object='rtcp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o rtcp.lo `test -f 'rtcp/rtcp.c' || echo '$(srcdir)/'`rtcp/rtcp.c

udp.lo: rtp/udp.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT udp.lo -MD -MP -MF $(DEPDIR)/udp.Tpo -c -o udp.lo `test -f 'rtp/udp.c' || echo '$(srcdir)/'`rtp/udp.c
	$(am__mv) $(DEPDIR)/udp.Tpo $(DEPDIR)/udp.Plo
#	source='rtp/udp.c' object='udp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o udp.lo `test -f 'rtp/udp.c' || echo '$(srcdir)/'`rtp/udp.c

tcp.lo: rtp/tcp.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT tcp.lo -MD -MP -MF $(DEPDIR)/tcp.Tpo -c -o tcp.lo `test -f 'rtp/tcp.c' || echo '$(srcdir)/'`rtp/tcp.c
	$(am__mv) $(DEPDIR)/tcp.Tpo $(DEPDIR)/tcp.Plo
#	source='rtp/tcp.c' object='tcp.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o tcp.lo `test -f 'rtp/tcp.c' || echo '$(srcdir)/'`rtp/tcp.c

socket.lo: net/socket.c
	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT socket.lo -MD -MP -MF $(DEPDIR)/socket.Tpo -c -o socket.lo `test -f 'net/socket.c' || echo '$(srcdir)/'`net/socket.c
	$(am__mv) $(DEPDIR)/socket.Tpo $(DEPDIR)/socket.Plo
#	source='net/socket.c' object='socket.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o socket.lo `test -f 'net/socket.c' || echo '$(srcdir)/'`net/socket.c

rtspd-version.o: comm/version.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-version.o -MD -MP -MF $(DEPDIR)/rtspd-version.Tpo -c -o rtspd-version.o `test -f 'comm/version.c' || echo '$(srcdir)/'`comm/version.c
	$(am__mv) $(DEPDIR)/rtspd-version.Tpo $(DEPDIR)/rtspd-version.Po
#	source='comm/version.c' object='rtspd-version.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-version.o `test -f 'comm/version.c' || echo '$(srcdir)/'`comm/version.c

rtspd-version.obj: comm/version.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-version.obj -MD -MP -MF $(DEPDIR)/rtspd-version.Tpo -c -o rtspd-version.obj `if test -f 'comm/version.c'; then $(CYGPATH_W) 'comm/version.c'; else $(CYGPATH_W) '$(srcdir)/comm/version.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-version.Tpo $(DEPDIR)/rtspd-version.Po
#	source='comm/version.c' object='rtspd-version.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-version.obj `if test -f 'comm/version.c'; then $(CYGPATH_W) 'comm/version.c'; else $(CYGPATH_W) '$(srcdir)/comm/version.c'; fi`

rtspd-parese_conf.o: comm/parese_conf.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-parese_conf.o -MD -MP -MF $(DEPDIR)/rtspd-parese_conf.Tpo -c -o rtspd-parese_conf.o `test -f 'comm/parese_conf.c' || echo '$(srcdir)/'`comm/parese_conf.c
	$(am__mv) $(DEPDIR)/rtspd-parese_conf.Tpo $(DEPDIR)/rtspd-parese_conf.Po
#	source='comm/parese_conf.c' object='rtspd-parese_conf.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-parese_conf.o `test -f 'comm/parese_conf.c' || echo '$(srcdir)/'`comm/parese_conf.c

rtspd-parese_conf.obj: comm/parese_conf.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-parese_conf.obj -MD -MP -MF $(DEPDIR)/rtspd-parese_conf.Tpo -c -o rtspd-parese_conf.obj `if test -f 'comm/parese_conf.c'; then $(CYGPATH_W) 'comm/parese_conf.c'; else $(CYGPATH_W) '$(srcdir)/comm/parese_conf.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-parese_conf.Tpo $(DEPDIR)/rtspd-parese_conf.Po
#	source='comm/parese_conf.c' object='rtspd-parese_conf.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-parese_conf.obj `if test -f 'comm/parese_conf.c'; then $(CYGPATH_W) 'comm/parese_conf.c'; else $(CYGPATH_W) '$(srcdir)/comm/parese_conf.c'; fi`

rtspd-md5c.o: comm/md5c.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-md5c.o -MD -MP -MF $(DEPDIR)/rtspd-md5c.Tpo -c -o rtspd-md5c.o `test -f 'comm/md5c.c' || echo '$(srcdir)/'`comm/md5c.c
	$(am__mv) $(DEPDIR)/rtspd-md5c.Tpo $(DEPDIR)/rtspd-md5c.Po
#	source='comm/md5c.c' object='rtspd-md5c.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-md5c.o `test -f 'comm/md5c.c' || echo '$(srcdir)/'`comm/md5c.c

rtspd-md5c.obj: comm/md5c.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-md5c.obj -MD -MP -MF $(DEPDIR)/rtspd-md5c.Tpo -c -o rtspd-md5c.obj `if test -f 'comm/md5c.c'; then $(CYGPATH_W) 'comm/md5c.c'; else $(CYGPATH_W) '$(srcdir)/comm/md5c.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-md5c.Tpo $(DEPDIR)/rtspd-md5c.Po
#	source='comm/md5c.c' object='rtspd-md5c.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-md5c.obj `if test -f 'comm/md5c.c'; then $(CYGPATH_W) 'comm/md5c.c'; else $(CYGPATH_W) '$(srcdir)/comm/md5c.c'; fi`

rtspd-rtsp_comm_fun.o: rtsp/rtsp_comm_fun.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_comm_fun.o -MD -MP -MF $(DEPDIR)/rtspd-rtsp_comm_fun.Tpo -c -o rtspd-rtsp_comm_fun.o `test -f 'rtsp/rtsp_comm_fun.c' || echo '$(srcdir)/'`rtsp/rtsp_comm_fun.c
	$(am__mv) $(DEPDIR)/rtspd-rtsp_comm_fun.Tpo $(DEPDIR)/rtspd-rtsp_comm_fun.Po
#	source='rtsp/rtsp_comm_fun.c' object='rtspd-rtsp_comm_fun.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_comm_fun.o `test -f 'rtsp/rtsp_comm_fun.c' || echo '$(srcdir)/'`rtsp/rtsp_comm_fun.c

rtspd-rtsp_comm_fun.obj: rtsp/rtsp_comm_fun.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_comm_fun.obj -MD -MP -MF $(DEPDIR)/rtspd-rtsp_comm_fun.Tpo -c -o rtspd-rtsp_comm_fun.obj `if test -f 'rtsp/rtsp_comm_fun.c'; then $(CYGPATH_W) 'rtsp/rtsp_comm_fun.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_comm_fun.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-rtsp_comm_fun.Tpo $(DEPDIR)/rtspd-rtsp_comm_fun.Po
#	source='rtsp/rtsp_comm_fun.c' object='rtspd-rtsp_comm_fun.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_comm_fun.obj `if test -f 'rtsp/rtsp_comm_fun.c'; then $(CYGPATH_W) 'rtsp/rtsp_comm_fun.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_comm_fun.c'; fi`

rtspd-rtsp_options.o: rtsp/rtsp_options.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_options.o -MD -MP -MF $(DEPDIR)/rtspd-rtsp_options.Tpo -c -o rtspd-rtsp_options.o `test -f 'rtsp/rtsp_options.c' || echo '$(srcdir)/'`rtsp/rtsp_options.c
	$(am__mv) $(DEPDIR)/rtspd-rtsp_options.Tpo $(DEPDIR)/rtspd-rtsp_options.Po
#	source='rtsp/rtsp_options.c' object='rtspd-rtsp_options.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_options.o `test -f 'rtsp/rtsp_options.c' || echo '$(srcdir)/'`rtsp/rtsp_options.c

rtspd-rtsp_options.obj: rtsp/rtsp_options.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_options.obj -MD -MP -MF $(DEPDIR)/rtspd-rtsp_options.Tpo -c -o rtspd-rtsp_options.obj `if test -f 'rtsp/rtsp_options.c'; then $(CYGPATH_W) 'rtsp/rtsp_options.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_options.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-rtsp_options.Tpo $(DEPDIR)/rtspd-rtsp_options.Po
#	source='rtsp/rtsp_options.c' object='rtspd-rtsp_options.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_options.obj `if test -f 'rtsp/rtsp_options.c'; then $(CYGPATH_W) 'rtsp/rtsp_options.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_options.c'; fi`

rtspd-rtsp_describe.o: rtsp/rtsp_describe.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_describe.o -MD -MP -MF $(DEPDIR)/rtspd-rtsp_describe.Tpo -c -o rtspd-rtsp_describe.o `test -f 'rtsp/rtsp_describe.c' || echo '$(srcdir)/'`rtsp/rtsp_describe.c
	$(am__mv) $(DEPDIR)/rtspd-rtsp_describe.Tpo $(DEPDIR)/rtspd-rtsp_describe.Po
#	source='rtsp/rtsp_describe.c' object='rtspd-rtsp_describe.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_describe.o `test -f 'rtsp/rtsp_describe.c' || echo '$(srcdir)/'`rtsp/rtsp_describe.c

rtspd-rtsp_describe.obj: rtsp/rtsp_describe.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_describe.obj -MD -MP -MF $(DEPDIR)/rtspd-rtsp_describe.Tpo -c -o rtspd-rtsp_describe.obj `if test -f 'rtsp/rtsp_describe.c'; then $(CYGPATH_W) 'rtsp/rtsp_describe.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_describe.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-rtsp_describe.Tpo $(DEPDIR)/rtspd-rtsp_describe.Po
#	source='rtsp/rtsp_describe.c' object='rtspd-rtsp_describe.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_describe.obj `if test -f 'rtsp/rtsp_describe.c'; then $(CYGPATH_W) 'rtsp/rtsp_describe.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_describe.c'; fi`

rtspd-rtsp_setup.o: rtsp/rtsp_setup.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_setup.o -MD -MP -MF $(DEPDIR)/rtspd-rtsp_setup.Tpo -c -o rtspd-rtsp_setup.o `test -f 'rtsp/rtsp_setup.c' || echo '$(srcdir)/'`rtsp/rtsp_setup.c
	$(am__mv) $(DEPDIR)/rtspd-rtsp_setup.Tpo $(DEPDIR)/rtspd-rtsp_setup.Po
#	source='rtsp/rtsp_setup.c' object='rtspd-rtsp_setup.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_setup.o `test -f 'rtsp/rtsp_setup.c' || echo '$(srcdir)/'`rtsp/rtsp_setup.c

rtspd-rtsp_setup.obj: rtsp/rtsp_setup.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_setup.obj -MD -MP -MF $(DEPDIR)/rtspd-rtsp_setup.Tpo -c -o rtspd-rtsp_setup.obj `if test -f 'rtsp/rtsp_setup.c'; then $(CYGPATH_W) 'rtsp/rtsp_setup.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_setup.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-rtsp_setup.Tpo $(DEPDIR)/rtspd-rtsp_setup.Po
#	source='rtsp/rtsp_setup.c' object='rtspd-rtsp_setup.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_setup.obj `if test -f 'rtsp/rtsp_setup.c'; then $(CYGPATH_W) 'rtsp/rtsp_setup.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_setup.c'; fi`

rtspd-rtsp_play.o: rtsp/rtsp_play.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_play.o -MD -MP -MF $(DEPDIR)/rtspd-rtsp_play.Tpo -c -o rtspd-rtsp_play.o `test -f 'rtsp/rtsp_play.c' || echo '$(srcdir)/'`rtsp/rtsp_play.c
	$(am__mv) $(DEPDIR)/rtspd-rtsp_play.Tpo $(DEPDIR)/rtspd-rtsp_play.Po
#	source='rtsp/rtsp_play.c' object='rtspd-rtsp_play.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_play.o `test -f 'rtsp/rtsp_play.c' || echo '$(srcdir)/'`rtsp/rtsp_play.c

rtspd-rtsp_play.obj: rtsp/rtsp_play.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_play.obj -MD -MP -MF $(DEPDIR)/rtspd-rtsp_play.Tpo -c -o rtspd-rtsp_play.obj `if test -f 'rtsp/rtsp_play.c'; then $(CYGPATH_W) 'rtsp/rtsp_play.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_play.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-rtsp_play.Tpo $(DEPDIR)/rtspd-rtsp_play.Po
#	source='rtsp/rtsp_play.c' object='rtspd-rtsp_play.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_play.obj `if test -f 'rtsp/rtsp_play.c'; then $(CYGPATH_W) 'rtsp/rtsp_play.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_play.c'; fi`

rtspd-rtsp_teardown.o: rtsp/rtsp_teardown.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_teardown.o -MD -MP -MF $(DEPDIR)/rtspd-rtsp_teardown.Tpo -c -o rtspd-rtsp_teardown.o `test -f 'rtsp/rtsp_teardown.c' || echo '$(srcdir)/'`rtsp/rtsp_teardown.c
	$(am__mv) $(DEPDIR)/rtspd-rtsp_teardown.Tpo $(DEPDIR)/rtspd-rtsp_teardown.Po
#	source='rtsp/rtsp_teardown.c' object='rtspd-rtsp_teardown.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_teardown.o `test -f 'rtsp/rtsp_teardown.c' || echo '$(srcdir)/'`rtsp/rtsp_teardown.c

rtspd-rtsp_teardown.obj: rtsp/rtsp_teardown.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_teardown.obj -MD -MP -MF $(DEPDIR)/rtspd-rtsp_teardown.Tpo -c -o rtspd-rtsp_teardown.obj `if test -f 'rtsp/rtsp_teardown.c'; then $(CYGPATH_W) 'rtsp/rtsp_teardown.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_teardown.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-rtsp_teardown.Tpo $(DEPDIR)/rtspd-rtsp_teardown.Po
#	source='rtsp/rtsp_teardown.c' object='rtspd-rtsp_teardown.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_teardown.obj `if test -f 'rtsp/rtsp_teardown.c'; then $(CYGPATH_W) 'rtsp/rtsp_teardown.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_teardown.c'; fi`

rtspd-rtsp_status.o: rtsp/rtsp_status.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_status.o -MD -MP -MF $(DEPDIR)/rtspd-rtsp_status.Tpo -c -o rtspd-rtsp_status.o `test -f 'rtsp/rtsp_status.c' || echo '$(srcdir)/'`rtsp/rtsp_status.c
	$(am__mv) $(DEPDIR)/rtspd-rtsp_status.Tpo $(DEPDIR)/rtspd-rtsp_status.Po
#	source='rtsp/rtsp_status.c' object='rtspd-rtsp_status.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_status.o `test -f 'rtsp/rtsp_status.c' || echo '$(srcdir)/'`rtsp/rtsp_status.c

rtspd-rtsp_status.obj: rtsp/rtsp_status.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtsp_status.obj -MD -MP -MF $(DEPDIR)/rtspd-rtsp_status.Tpo -c -o rtspd-rtsp_status.obj `if test -f 'rtsp/rtsp_status.c'; then $(CYGPATH_W) 'rtsp/rtsp_status.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_status.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-rtsp_status.Tpo $(DEPDIR)/rtspd-rtsp_status.Po
#	source='rtsp/rtsp_status.c' object='rtspd-rtsp_status.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtsp_status.obj `if test -f 'rtsp/rtsp_status.c'; then $(CYGPATH_W) 'rtsp/rtsp_status.c'; else $(CYGPATH_W) '$(srcdir)/rtsp/rtsp_status.c'; fi`

rtspd-rtp_h264.o: rtp/rtp_h264.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtp_h264.o -MD -MP -MF $(DEPDIR)/rtspd-rtp_h264.Tpo -c -o rtspd-rtp_h264.o `test -f 'rtp/rtp_h264.c' || echo '$(srcdir)/'`rtp/rtp_h264.c
	$(am__mv) $(DEPDIR)/rtspd-rtp_h264.Tpo $(DEPDIR)/rtspd-rtp_h264.Po
#	source='rtp/rtp_h264.c' object='rtspd-rtp_h264.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtp_h264.o `test -f 'rtp/rtp_h264.c' || echo '$(srcdir)/'`rtp/rtp_h264.c

rtspd-rtp_h264.obj: rtp/rtp_h264.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtp_h264.obj -MD -MP -MF $(DEPDIR)/rtspd-rtp_h264.Tpo -c -o rtspd-rtp_h264.obj `if test -f 'rtp/rtp_h264.c'; then $(CYGPATH_W) 'rtp/rtp_h264.c'; else $(CYGPATH_W) '$(srcdir)/rtp/rtp_h264.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-rtp_h264.Tpo $(DEPDIR)/rtspd-rtp_h264.Po
#	source='rtp/rtp_h264.c' object='rtspd-rtp_h264.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtp_h264.obj `if test -f 'rtp/rtp_h264.c'; then $(CYGPATH_W) 'rtp/rtp_h264.c'; else $(CYGPATH_W) '$(srcdir)/rtp/rtp_h264.c'; fi`

rtspd-rtcp.o: rtcp/rtcp.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtcp.o -MD -MP -MF $(DEPDIR)/rtspd-rtcp.Tpo -c -o rtspd-rtcp.o `test -f 'rtcp/rtcp.c' || echo '$(srcdir)/'`rtcp/rtcp.c
	$(am__mv) $(DEPDIR)/rtspd-rtcp.Tpo $(DEPDIR)/rtspd-rtcp.Po
#	source='rtcp/rtcp.c' object='rtspd-rtcp.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtcp.o `test -f 'rtcp/rtcp.c' || echo '$(srcdir)/'`rtcp/rtcp.c

rtspd-rtcp.obj: rtcp/rtcp.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtcp.obj -MD -MP -MF $(DEPDIR)/rtspd-rtcp.Tpo -c -o rtspd-rtcp.obj `if test -f 'rtcp/rtcp.c'; then $(CYGPATH_W) 'rtcp/rtcp.c'; else $(CYGPATH_W) '$(srcdir)/rtcp/rtcp.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-rtcp.Tpo $(DEPDIR)/rtspd-rtcp.Po
#	source='rtcp/rtcp.c' object='rtspd-rtcp.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtcp.obj `if test -f 'rtcp/rtcp.c'; then $(CYGPATH_W) 'rtcp/rtcp.c'; else $(CYGPATH_W) '$(srcdir)/rtcp/rtcp.c'; fi`

rtspd-udp.o: rtp/udp.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-udp.o -MD -MP -MF $(DEPDIR)/rtspd-udp.Tpo -c -o rtspd-udp.o `test -f 'rtp/udp.c' || echo '$(srcdir)/'`rtp/udp.c
	$(am__mv) $(DEPDIR)/rtspd-udp.Tpo $(DEPDIR)/rtspd-udp.Po
#	source='rtp/udp.c' object='rtspd-udp.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-udp.o `test -f 'rtp/udp.c' || echo '$(srcdir)/'`rtp/udp.c

rtspd-udp.obj: rtp/udp.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-udp.obj -MD -MP -MF $(DEPDIR)/rtspd-udp.Tpo -c -o rtspd-udp.obj `if test -f 'rtp/udp.c'; then $(CYGPATH_W) 'rtp/udp.c'; else $(CYGPATH_W) '$(srcdir)/rtp/udp.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-udp.Tpo $(DEPDIR)/rtspd-udp.Po
#	source='rtp/udp.c' object='rtspd-udp.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-udp.obj `if test -f 'rtp/udp.c'; then $(CYGPATH_W) 'rtp/udp.c'; else $(CYGPATH_W) '$(srcdir)/rtp/udp.c'; fi`

rtspd-tcp.o: rtp/tcp.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-tcp.o -MD -MP -MF $(DEPDIR)/rtspd-tcp.Tpo -c -o rtspd-tcp.o `test -f 'rtp/tcp.c' || echo '$(srcdir)/'`rtp/tcp.c
	$(am__mv) $(DEPDIR)/rtspd-tcp.Tpo $(DEPDIR)/rtspd-tcp.Po
#	source='rtp/tcp.c' object='rtspd-tcp.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-tcp.o `test -f 'rtp/tcp.c' || echo '$(srcdir)/'`rtp/tcp.c

rtspd-tcp.obj: rtp/tcp.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-tcp.obj -MD -MP -MF $(DEPDIR)/rtspd-tcp.Tpo -c -o rtspd-tcp.obj `if test -f 'rtp/tcp.c'; then $(CYGPATH_W) 'rtp/tcp.c'; else $(CYGPATH_W) '$(srcdir)/rtp/tcp.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-tcp.Tpo $(DEPDIR)/rtspd-tcp.Po
#	source='rtp/tcp.c' object='rtspd-tcp.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-tcp.obj `if test -f 'rtp/tcp.c'; then $(CYGPATH_W) 'rtp/tcp.c'; else $(CYGPATH_W) '$(srcdir)/rtp/tcp.c'; fi`

rtspd-socket.o: net/socket.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-socket.o -MD -MP -MF $(DEPDIR)/rtspd-socket.Tpo -c -o rtspd-socket.o `test -f 'net/socket.c' || echo '$(srcdir)/'`net/socket.c
	$(am__mv) $(DEPDIR)/rtspd-socket.Tpo $(DEPDIR)/rtspd-socket.Po
#	source='net/socket.c' object='rtspd-socket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-socket.o `test -f 'net/socket.c' || echo '$(srcdir)/'`net/socket.c

rtspd-socket.obj: net/socket.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-socket.obj -MD -MP -MF $(DEPDIR)/rtspd-socket.Tpo -c -o rtspd-socket.obj `if test -f 'net/socket.c'; then $(CYGPATH_W) 'net/socket.c'; else $(CYGPATH_W) '$(srcdir)/net/socket.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-socket.Tpo $(DEPDIR)/rtspd-socket.Po
#	source='net/socket.c' object='rtspd-socket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-socket.obj `if test -f 'net/socket.c'; then $(CYGPATH_W) 'net/socket.c'; else $(CYGPATH_W) '$(srcdir)/net/socket.c'; fi`

rtspd-rtspd.o: rtspd.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtspd.o -MD -MP -MF $(DEPDIR)/rtspd-rtspd.Tpo -c -o rtspd-rtspd.o `test -f 'rtspd.c' || echo '$(srcdir)/'`rtspd.c
	$(am__mv) $(DEPDIR)/rtspd-rtspd.Tpo $(DEPDIR)/rtspd-rtspd.Po
#	source='rtspd.c' object='rtspd-rtspd.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtspd.o `test -f 'rtspd.c' || echo '$(srcdir)/'`rtspd.c

rtspd-rtspd.obj: rtspd.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -MT rtspd-rtspd.obj -MD -MP -MF $(DEPDIR)/rtspd-rtspd.Tpo -c -o rtspd-rtspd.obj `if test -f 'rtspd.c'; then $(CYGPATH_W) 'rtspd.c'; else $(CYGPATH_W) '$(srcdir)/rtspd.c'; fi`
	$(am__mv) $(DEPDIR)/rtspd-rtspd.Tpo $(DEPDIR)/rtspd-rtspd.Po
#	source='rtspd.c' object='rtspd-rtspd.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rtspd_CFLAGS) $(CFLAGS) -c -o rtspd-rtspd.obj `if test -f 'rtspd.c'; then $(CYGPATH_W) 'rtspd.c'; else $(CYGPATH_W) '$(srcdir)/rtspd.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) config.h
install-binPROGRAMS: install-libLTLIBRARIES

installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS install-libLTLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-libLTLIBRARIES

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool ctags dist dist-all dist-bzip2 dist-gzip \
	dist-lzma dist-shar dist-tarZ dist-xz dist-zip distcheck \
	distclean distclean-compile distclean-generic distclean-hdr \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-libLTLIBRARIES install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-libLTLIBRARIES


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
